### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by ShivaniRavi97** [jadkins89/Recipe-Scraper#13]
Could you please describe how to execute this file?
Like the steps for execution.

**Comment by ShivaniRavi97** [comment]
Could you do the same for some Indian website ?
Your work is great! Thanks alot this helps alot.

**Comment by jadkins89** [comment]
Most website can be done, depending on the visibility of their HTML via an HTTP client or headless browser like puppeteer. As far as describing how to execute the code, it's wrapped up in a package that you can install via npm. If you wish to fork the code and run it locally you'd use the function ```recipeScraper``` from ```scrapers/index.js```.

I'm unsure of how else to describe execution. Are you running into a problem?

**Comment by ShivaniRavi97** [comment]
Yes. i am unable to run the code

**Comment by jadkins89** [comment]
Have you installed via npm? Is recipe-scraper in your package.json dependencies? Did you follow this general layout?

```javascript
// import the module
const recipeScraper = require("recipe-scraper");
 
// enter a supported recipe url as a parameter - returns a promise
async function someAsyncFunc() {
  ...
  let recipe = await recipeScraper("some.recipe.url");
  ...
}
 
// using Promise chaining
recipeScraper("some.recipe.url").then(recipe => {
    // do something with recipe
}).catch(error => {
    // do something with error
});
```

**Comment by ShivaniRavi97** [comment]
>npm run start

> recipe-scraper@1.13.0 start D:\final year project\github_web\Recipe-Scraper-master\Recipe-Scraper-master
> node scrapers/index.js

**Comment by ShivaniRavi97** [comment]
It comes till here .......and  the log ends.

**Comment by ShivaniRavi97** [comment]
I did npm install. And whatever was in package.jon it got installed.
Nope the package.json doesn't have recipe-scraper...i tried installing it but it is throwing and error like this--
npm install recipe-scraper
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "recipe-scraper" under a package
npm ERR! also called "recipe-scraper". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivani\AppData\Roaming\npm-cache\_logs\2020-03-15T19_37_53_937Z-debug.log

**Comment by jadkins89** [comment]
You are getting an error since your project has the same name as this package. Change the name of your project in package.json to remedy this.

Above it appears that you are simply running the code, which won't do anything since this is a utility. The code as it is, is creating a function called ```recipeScraper``` but it isn't executed since it's meant to be added into other projects. If you'd like to run it immediately you'd need to execute the function with some url as a parameter.

**Comment by ShivaniRavi97** [comment]
const recipeScraper = url => {
  let domain = parseDomain(url).domain;
  return new Promise((resolve, reject) => {
    if (domains[domain] !== undefined) {
      resolve(domains[domain](url));
    } else {
      reject(new Error("Site not yet supported"));
    }
  });
};

So, here in this code ...i should replace url with something like this?

const recipeScraper = url => {
  let domain = parseDomain(https://m.tarladalal.com/recipes-for-Andhra-1204).domain;
  return new Promise((resolve, reject) => {
    if (domains[domain] !== undefined) {
      resolve(domains[domain](url));
    } else {
      reject(new Error("Site not yet supported"));
    }
  });
};

**Comment by ShivaniRavi97** [comment]
// import the module
const recipeScraper = require("recipe-scraper");
 
// enter a supported recipe url as a parameter - returns a promise
async function someAsyncFunc() {
  ...
  let recipe = await recipeScraper("some.recipe.url");
  ...
}
 
// using Promise chaining
recipeScraper("some.recipe.url").then(recipe => {
    // do something with recipe
}).catch(error => {
    // do something with error
});


Where should i use this code??

**Comment by jadkins89** [comment]
I would suggest reading up on how to use npm packages https://docs.npmjs.com/using-npm-packages-in-your-projects and possibly study up on NodeJS. This scraper will not work for tarladalal.com currently and only has scrapers written for the websites I listed in the ReadMe. If you'd like to run some test code without using the npm package. You could add something like this to index.js: 

```javascript
recipeScraper('https://www.allrecipes.com/recipe/21033/korean-bbq-chicken-marinade/')
.then(recipe => {
     console.log(recipe);
});
```

**Comment by ShivaniRavi97** [comment]
Thank you soo much.I got it now.
How could i use this for some indian website? Because i am try to do the same thing for recipes from an indian website.

**Comment by jadkins89** [comment]
I currently have each website broken into its own scrape in the scrapers folder. Study those and see how they work. You can likely do that with most indian websites in a similar manner. You just need to find some identifying attributes in the HTML that you can single out to get their data.

Here's an intro video on doing web scraping with NodeJS that is done in a similar fashion to this package https://www.youtube.com/watch?v=LoziivfAAjE
