### ISSUE TITLE
Site request: kitchenstories.com

### ISSUE THREAD

**Issue by vaviary** [jadkins89/Recipe-Scraper#15]
Hi there,
Congratulations on this great project! Is there any chance you could add support for [Kitchen Stories](https://www.kitchenstories.com/en)? It’s a quite popular recipe site in Germany.

Here’s an [example recipe](https://www.kitchenstories.com/en/recipes/chinese-cold-noodles).

Let me know in case you have any questions.

**Comment by jadkins89** [comment]
Just added it and published the update to npm. It should work for either english or german versions of the site.
