### ISSUE TITLE
JSON Recipe Shema from schema.org

### ISSUE THREAD

**Issue by TheMBeat** [jadkins89/Recipe-Scraper#16]
Wouldn't a switch to the JSON Recipe Shema from schema.org be useful?
Furthermore, many recipes in this schema are already available on these pages.

**Comment by jadkins89** [comment]
IIRC schema.org is primarily used for markup which doesn't pertain to this project. If you mean simply updating the object to have keys that match the schema.org recipe schema that would be a breaking update for current developers. Some of the data in that schema isn't currently being scraped as well.

If I end up making a new version that includes additional data I may consider using a structure like the one from schema.org. For now, if developers are using this module with schema markup it would be very simple to create a JSON-LD object from the result of a scrape.

Please let me know if you have additional insight I may have glanced over.
