### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by tannerfiscus** [jadkins89/Recipe-Scraper#22]
Hi there, this package is really awesome! It would be great if you could support minimalistbaker.com.

I also was playing with the package for the first time tonight and noticed that it always logs a grilled cheese recipe in addition to the one requested. I think that might have slipped in here: https://github.com/jadkins89/Recipe-Scraper/blob/5fabacced9774d20a80b8a8134c1a1371d0098be/scrapers/index.js#L55-L57

Thanks so much for building this!

**Comment by jadkins89** [comment]
🙏 Thank you for pointing that out, that's an artifact from my dev code for a recent site I added. I'll look at adding minimalistbaker.com this weekend. I pushed a bug update to the npm package that removes that log.

**Comment by tannerfiscus** [comment]
No problem 👍  Thank you!

**Comment by jadkins89** [comment]
I just added minimalistbaker.com, please do some quality assurance if you have some time and let me know if you see any issues.

**Comment by tannerfiscus** [comment]
Thank you! It's working well 👌 

I noticed it's giving me another console error after upgrading about pioneer woman, which I think is coming from these lines: https://github.com/jadkins89/Recipe-Scraper/blob/c0f6d702249fb78b334baa789ace0f900f0172b0/scrapers/index.js#L56-L58

I appreciate your work on this :)

**Comment by jadkins89** [comment]
This will be the death of me! Case in point, don't code more after coding all day. I should write a script that yells at me to remove that dev code. I just published an update that removes it again. Thank you! 🤘
