### ISSUE TITLE
No Recipe's Found on centraltexasfoodbank.org

### ISSUE THREAD

**Issue by jesusnunezxoco** [jadkins89/Recipe-Scraper#23]
Hello!

I tried using the scraper yesterday centraltexasfoodbank.org, and I've gotten an error saying `Error: no recipe found on page`. I tried several urls, and one of my teammates tried it out on her computer, and we keep getting that error. We haven't found a recipe it works on anymore. Thank you!

**Comment by jesusnunezxoco** [comment]
I should mention I tested it on the Bon Appetit site and it did work on that.

**Comment by jadkins89** [comment]
Thanks for letting me know! I'll try to take a look tonight. It's probably a small change to their website that is throwing off the scrape now.

**Comment by jadkins89** [comment]
That was indeed the case, they took out some identifying information in their HTML. This site in particular seems to have several different formats so please let me know if you find a recipe that isn't working for it. It seems like they may use different templates sometimes or make adjustments to their html code on the fly which makes it somewhat unpredictable.

I published an update to npm that is working on the sample size I tested.
