### ISSUE TITLE
cooking.nytimes.com support

### ISSUE THREAD

**Issue by mattsarn** [jadkins89/Recipe-Scraper#24]
Example url:
https://cooking.nytimes.com/recipes/1017416-compound-butter

It's behind a paywall, but hoping we can set it up to accept user credentials to unlock content and then initiate the scraper.

**Comment by jadkins89** [comment]
I don't feel comfortable adding scrapes behind paywalls for this package, even with credentials. It is certainly doable though if you wanted to pursue it. There is plenty of documentation on how to login and set cookies using Puppeteer for instance.
