### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by flolep2607** [jadkins89/Recipe-Scraper#29]
pass just the html code without and the website called without passing the url

**Comment by jadkins89** [comment]
This would require some sort of standardized html that always had the recipe data in the same place or the use of something more complex to "guess" where the data lives. If you look through the code for this module, each website is more or less uniquely scraped.

**Comment by flolep2607** [comment]
I just want to say you get html from for example yummly so you pass this html in a module function with the website name

**Comment by jadkins89** [comment]
I see, that would be doable. I'll consider adding that feature in a future release. Thanks for the input!

**Comment by flolep2607** [comment]
Yor welcome 👍
