### ISSUE TITLE
Yummly not working

### ISSUE THREAD

**Issue by johnreiley** [jadkins89/Recipe-Scraper#30]
When attempting to scrape a recipe on yummly.com, I get back the error "No recipe found on page."

**Comment by flolep2607** [comment]
i have the same problem

**Comment by jadkins89** [comment]
I will address this soon, thank you for letting me know. I'm currently moving and thats taken up all my free time!

**Comment by thmsbdr** [comment]
@johnreiley Can you provide an example URL you're using?

**Comment by johnreiley** [comment]
https://www.yummly.com/recipe/Healthy-Chocolate-Banana-Brownies-9083669

**Comment by thmsbdr** [comment]
@johnreiley that recipe worked fine on my end. Are you running this in something like a cloud function with limited memory?

**Comment by johnreiley** [comment]
That could possibly be the issue but it looks like the service I’m using (Firebase functions) allows up to 2048MB of memory.

**Comment by thmsbdr** [comment]
@johnreiley thats the max but if you look at your function in the firebase console it's probably only set to 256MB. You should be able to increase it in the [Google Cloud Console](https://console.cloud.google.com/projectselector2/functions/list?supportedpurview=project)

**Comment by johnreiley** [comment]
Looks like that fixed it. 512MB wasn't enough so I had to bump it up to 1GB. Thanks for your help!
