### ISSUE TITLE
Adding a few sites

### ISSUE THREAD

**Issue by mattbloomfield** [jadkins89/Recipe-Scraper#35]
Hey man, thanks for making this. Love the setup. 

I added a few sites in a PR - let me know if you want it done differently. As I'm writing this I'm realizing you may have tests written that I didn't add to. 

Also, I wonder if it could be worth setting up some type of default fallback - I'm seeing that a lot of sites use the same Wordpress plugins and format things in the same ways.

**Comment by jadkins89** [comment]
Hey Matt, thank you so much for your contribution. I'll take a look at your PR soon. I've been trying to be more active on here but am in the middle of a home renovation along with working full time. 

I like the idea of having some fallback generic scrapes to try and capture some of the few common templates these sites are using. That should be easy enough to set up.

**Comment by mattbloomfield** [comment]
Congrats, man! We bought an old rental home 2 years ago and I'm not sure if there's any part of it we haven't touched at this point. Super fun project, but SO MUCH WORK haha.

**Comment by jadkins89** [comment]
Thanks again for the PR, I folded it into the code and will be publishing shortly. Sorry it took a month to get around to. If you'd like to collaborate on a generalized scrape let me know and we can work out the details.
