### ISSUE TITLE
Scrape search results from supported websites

### ISSUE THREAD

**Issue by redbrain** [jadkins89/Recipe-Scraper#43]
I'm not sure if this is in the scope of the package, but it would be a good feature to add.
In detail, passing a search term or a link to a search page would return a list of result links, which could be further parsed.

**Comment by jadkins89** [comment]
Thanks for the input, for now I am going to keep this as a simple recipe page scraper. In theory, someone could build a search term / results scraper API and use this tool in conjunction to scrape each linked page.
