### ISSUE TITLE
Switch to Typescript

### ISSUE THREAD

**Issue by josh18** [jadkins89/Recipe-Scraper#47]
I was planning on writing my own scraper but it's probably more useful for others if I contribute to this instead. I much prefer working with Typescript, would you accept a PR converting this project to Typescript?

Would understand completely if you don't want to.

Note I also found this library which seems kind of similar: https://github.com/thelifenadine/recipe-data-scraper

**Comment by jadkins89** [comment]
I'd gladly accept a PR that converts to TS. I've been using it at work the last year and can't imagine going back now. I checked out that other scraper. They are using JSON-LD which a recent contributor used for some scrapes. I'll likely add this in the future so we can have a generalized scrape to catch websites that don't have a dedicated one.

**Comment by josh18** [comment]
Just letting you know I decided not to do this as it seems pretty much all sites are using JSON-LD now so it was pretty easy to just roll my own.
