### ISSUE TITLE
Cannot resolve puppeteer/lib

### ISSUE THREAD

**Issue by squarepancakes** [jadkins89/Recipe-Scraper#5]
I am trying to use the recipe scrapper in my react app and is asking me to install puppeteer. 
common.js:23 ./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in '.../recipe-trial/node_modules/puppeteer/lib'

**Comment by jadkins89** [comment]
Puppeteer is a required dependency, it is used for a number of the scrapes; specifically ones that can't be scraped using simply request / cheerio. Do you have it installed?

**Comment by fredserva** [comment]
An old issue, but let's answer this anyway...

According to [this issue](https://github.com/puppeteer/puppeteer/issues/3466), you can't use Recipe-Scraper in a React app without declaring Puppeteer as an external in your webpack config file.
So, all you have do to is to declare it...

eg:
In my app, I have a `.webpack.config.js` in the root folder and here is its content :
```
module.exports = config => {
    config.target = 'electron-renderer';
    config.externals = {
        puppeteer: 'require("puppeteer")'
    };
    return config;
}
```

Works like a charm!
Hope this has been useful.
