### ISSUE TITLE
Allrecipes.com missing servings

### ISSUE THREAD

**Issue by lrobledo** [jadkins89/Recipe-Scraper#8]
Recipes from allrecipes.com are coming through without servings. It's a little hidden, but it's there: 
![image](https://user-images.githubusercontent.com/18466880/74004375-d6d99e80-4932-11ea-81c4-26a20a20b9b4.png)

```
<meta id="metaRecipeServings" itemprop="recipeYield" content="8">
```

**Comment by jadkins89** [comment]
Good catch! I wonder if that was missing when I built the scrape originally. Either way, I'll push an update later today.

**Comment by jadkins89** [comment]
This should be resolved, I just published an update to npm and fixed eatingwell which was broken because of a site update.
